### ISSUE TITLE
2.x branch

### ISSUE THREAD

**Issue by uberhacker** [terminus-plugin-project/terminus-snowman-plugin#1]
Don't we want a 2.x branch and 2.0.0 tag since this is only compatible with Terminus 2.x?

**Comment by rvtraveller** [comment]
I had left it as master because I wasn't intending to support 1.x (or 0.x...) But we can switch it.

**Comment by uberhacker** [comment]
I imagine it might be a problem if Terminus 3.x is released but OK until then, I guess.
