### ISSUE TITLE
Autoload path still wrong...?

### ISSUE THREAD

**Issue by bwood** [terminus-plugin-project/terminus-snowman-plugin#4]
I see this was maybe addressed in https://github.com/terminus-plugin-project/terminus-snowman-plugin/issues/2#issuecomment-488427431, but the version I just cloned still had the problem.  

Created a PR: https://github.com/terminus-plugin-project/terminus-snowman-plugin/pull/3

**Comment by rvtraveller** [comment]
Merged the PR and will tag a new release. Thanks for catching this one!
